### ISSUE TITLE
Milestone 2 To-do List

### ISSUE THREAD

**Issue by danfke** [UBC-MDS/525_group9#13]
**Pavel**:
- [x] Setup your EC2 instance
- [x] Setup your JupyterHub

**Rong**:
- [x] Setup the server

**Sukhleen**
- [x] Get the data what we wrangled in our first milestone
- [x] Setup your S3 bucket and move data

**Daniel**
- [x] Wrangle the data in preparation for machine learning
- [x] **Optional** Benchmarking:
- - [x]  How long did it take to read Parquet file from local disk?
- - [x] Parquet file from S3?
- - [x] CSV file from S3?

- [x] **Proof-reading and submission**: Sukhleen

**Comment by lirnish** [comment]
done
