### ISSUE TITLE
Milestone 3

### ISSUE THREAD

**Issue by lirnish** [UBC-MDS/525_group9#18]
- [x] Setup EMR cluster @plevchen 
- [x] Setup browser , jupyter environment & connect to the master node. @lirnish
- [x] Develop a ML model using scikit-learn. @sukhleen999
- [x] Obtain best hyperparameter settings using spark's MLlib. @danfke 

Review
- [x] Proofread @plevchen 
- [x] Submitting to Canvas @plevchen
