### ISSUE TITLE
Milestone 4

### ISSUE THREAD

**Issue by sukhleen999** [UBC-MDS/525_group9#23]
- [x] Develop the API
- [x] Deploy the API
- [x] Summarize the journey from milestone 1 to 4

Proof reading and submission - @danfke
